[project]
name = "es-cicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "djangorestframework>=3.15.2",
    "drf-spectacular>=0.28.0",
    "ruff>=0.11.2",
]
